### ISSUE TITLE
Split lessons into pages

### ISSUE THREAD

**Issue by tschoffelen** [rchain-community/rholang-lessons#6]

**Comment by le-dawg** [comment]
What is the general status on this prject/repo ? Need any help ?

**Comment by tschoffelen** [comment]
I unfortunately haven't had any time to finish this, so yes, please go ahead! 

Best to coordinate with @JoshOrndorff if you're interested in getting this project finished, it's his content that this app displays.

**Comment by JoshOrndorff** [comment]
@le-dawg I would love to get this working and integrated with rchain.coop. If you have the skills, we have the funds.

**Comment by JoshOrndorff** [comment]
I'm @JoshOrndorff on https://discord.gg/fvY8qhx

**Comment by le-dawg** [comment]
@tschoffelen did this project ever run ? 

`yarn build`
fails at the `react-static build` step (the first) with a 404 error. Do you know anything about this ?

**Comment by tschoffelen** [comment]
It used to work on my local environment, even put a compiled version online for Joshy at some point I think.

**Comment by tschoffelen** [comment]
Unfortunately on holiday at the moment and only have my phone, so cant test it...

**Comment by le-dawg** [comment]
I see. I will dabble with it when I feel like troubleshooting. Will do more doable stuff right away. 
I'd like to see how it looks like so I have a better concept of what's what. Was this like an a google lab ( "paginated markdowned content") or more like an embedded tutorial aka Cryptozombies ?

**Comment by le-dawg** [comment]
I have **exactly** the same issue with the `rchain-tutorial` in the `rchain ` repo. I noticed many similarities in the project structure. Is that online anywhere ?

My current thinking is that this is an environment issue on my laptop. I am trying to get it to run on windows with a fresh npm env.

**Comment by le-dawg** [comment]
All right, it was (as usual) much simpler than I thought - the 404 error was an actual https 404 and some cryptic DIY error message by some dependency.

Alas, paths needed to be fixed for the source material. There are other problems but I'll get to them eventually
